<?php
	
	namespace YiiMan\Setting\assets;
	use yii\web\AssetBundle;
	
	/**
	 * Created by YiiMan.
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Site:http://yiiman.ir
	 * Date: 12/29/2018
	 * Time: 2:43 PM
	 */
	class AdminBgImagesAssets extends AssetBundle {
		public function init() {
			parent::init(); // TODO: Change the autogenerated stub
			$this->sourcePath = realpath( __DIR__ . '/files/images' );
		}
	}
