<?php
	
	namespace YiiMan\Setting\widgets;
	
	use YiiMan\Setting\assets\FileSelectorAsset;
	use yii\widgets\InputWidget;
	
	/**
	 * Created by YiiMan .
	 * Programmer: gholamreza beheshtian
	 * Mobile:09353466620
	 * Site:http://yiiman.ir
	 * Date: 12/30/2018
	 * Time: 4:05 AM
	 */
	class FileSelectorWidget extends InputWidget {
		public $multiple = false;
		
		
		public function run() {
			
			
			parent::run(); // TODO: Change the autogenerated stub
			FileSelectorAsset::register( $this->view );
			echo $this->render(
				'@YiiMan/src/widgets/views/fileSelect.php' ,
				[
					'id'        => $this->id ,
					'name'      => $this->name ,
					'label'     => $this->model->getAttributeLabel(
						$this->attribute
					) ,
					'model'     => $this->model ,
					'attribute' => $this->attribute ,
					'value'     => $this->value ,

				]
			);
		}
	}
