<?php
/**
 * Created by YiiMan.
 * Programmer: gholamreza beheshtian
 * Mobile:09353466620
 * Site:http://yiiman.ir
 * Date: ۱۷/۰۴/۲۰۲۰
 * Time: ۰۳:۵۰ قبل‌ازظهر
 */

namespace YiiMan\Setting\widgets;


use kartik\base\InputWidget;

class ImageSelectWidget extends InputWidget
{
    public $images = [];

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('imageSelect', ['images' => $this->images, 'name' => $this->name, 'value' => $this->value]);
    }
}
