<?php
	
	namespace YiiMan\Setting\module\widgets;
	
	use system\modules\filemanager\assets\FileSelectorAsset;
	use yii\base\Widget;
	use yii\widgets\InputWidget;
	
	
	class MediaViewWidget extends Widget {
		public $model;
		public $attribute;
		public $count;
		
		public function run() {
			parent::run(); // TODO: Change the autogenerated stub
//			FileSelectorAsset::register( $this->view );
			$css=<<<CSS
.demo-gallery {
	position: absolute;
	top: 7px;
	left: 323px;
	right: auto;
	float: none;

}
.demo-gallery > ul > li a {
	/* border: 3px solid #FFF; */

	display: block;
	overflow: hidden;
	position: relative;
	float: left;
	border-radius: 5px;
	box-shadow: 0 5px 15px -8px rgba(0,0,0,.24),0 8px 10px -5px rgba(0,0,0,.2);
	width: 100%;
	height: 105px;
	padding: 20px;
}
CSS;

			$this->view->registerCss($css);
			echo $this->render(
				'@system/modules/setting/widgets/views/widgetView.php' ,
				[
					'model'     => $this->model ,
					'attribute' => $this->attribute ,
					'id'        => $this->attribute ,
					'count'     => $this->count
				]
			);
		}
	}
